
package xmlws.firma.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankaWs", targetNamespace = "http://soap.service.poslovna.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankaWs {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "handleUplata", targetNamespace = "http://soap.service.poslovna.com/", className = "xmlws.firma.jaxws.HandleUplata")
    @ResponseWrapper(localName = "handleUplataResponse", targetNamespace = "http://soap.service.poslovna.com/", className = "xmlws.firma.jaxws.HandleUplataResponse")
    @Action(input = "http://soap.service.poslovna.com/BankaWs/handleUplataRequest", output = "http://soap.service.poslovna.com/BankaWs/handleUplataResponse")
    public String handleUplata(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
