
package xmlws.firma.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPTestI", targetNamespace = "http://soap.service.poslovna.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAPTestI {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTestData", targetNamespace = "http://soap.service.poslovna.com/", className = "xmlws.firma.ws.GetTestData")
    @ResponseWrapper(localName = "getTestDataResponse", targetNamespace = "http://soap.service.poslovna.com/", className = "xmlws.firma.ws.GetTestDataResponse")
    @Action(input = "http://soap.service.poslovna.com/SOAPTestI/getTestDataRequest", output = "http://soap.service.poslovna.com/SOAPTestI/getTestDataResponse")
    public List<String> getTestData();

}
