
package xmlws.firma.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SOAPTestService", targetNamespace = "http://soap.service.poslovna.com/", wsdlLocation = "http://localhost:8089/test1/1?wsdl")
public class SOAPTestService
    extends Service
{

    private final static URL SOAPTESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPTESTSERVICE_EXCEPTION;
    private final static QName SOAPTESTSERVICE_QNAME = new QName("http://soap.service.poslovna.com/", "SOAPTestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/test1/1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPTESTSERVICE_WSDL_LOCATION = url;
        SOAPTESTSERVICE_EXCEPTION = e;
    }

    public SOAPTestService() {
        super(__getWsdlLocation(), SOAPTESTSERVICE_QNAME);
    }

    public SOAPTestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPTESTSERVICE_QNAME, features);
    }

    public SOAPTestService(URL wsdlLocation) {
        super(wsdlLocation, SOAPTESTSERVICE_QNAME);
    }

    public SOAPTestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPTESTSERVICE_QNAME, features);
    }

    public SOAPTestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPTestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SOAPTestI
     */
    @WebEndpoint(name = "SOAPTestPort")
    public SOAPTestI getSOAPTestPort() {
        return super.getPort(new QName("http://soap.service.poslovna.com/", "SOAPTestPort"), SOAPTestI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPTestI
     */
    @WebEndpoint(name = "SOAPTestPort")
    public SOAPTestI getSOAPTestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.poslovna.com/", "SOAPTestPort"), SOAPTestI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPTESTSERVICE_EXCEPTION!= null) {
            throw SOAPTESTSERVICE_EXCEPTION;
        }
        return SOAPTESTSERVICE_WSDL_LOCATION;
    }

}
